server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    username: root
    password: root
    url: "jdbc:mysql://localhost:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  signerKey: "OJfWofIdZSU2EBdUs6ucDLdAQCkFMVRiHe14X7UpulJmlIW0YVgYnZSlE5JcvrCr"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in second
app:
  services:
    profile: http://localhost:8081/profile

